### ISSUE TITLE
Do you have link to the presentation? 🙏 

### ISSUE THREAD

**Issue by developer239** [juristr/nx-extensibility-demo#1]

**Comment by juristr** [comment]
😅 this is the demo repo for the talk I'm giving this week at Nx Conf: https://nx.dev/conf

You should check it out. The link will be shared during the conf :)

**Comment by developer239** [comment]
![time-travel](https://user-images.githubusercontent.com/14946081/133306413-db4cd036-d521-4cd9-a7c9-88f53c67e485.gif)

**Comment by juristr** [comment]
https://docs.google.com/presentation/d/1mI4l1KFHujowQT6_CWLL52IhO25kqsIwmv36a3fnewg/edit?usp=sharing
